"""
Local web server for the book recommender.

Run with:
    python server.py [--debug] [--port 5050] [--model sonnet|haiku|opus] [--user NAME]

Then open http://localhost:5050 in your browser.

Multiple users are supported. Each user has their own profile (favourite
authors, genres and seed books) and their own state (current list, marks,
history), stored under users/<name>/. With no --user flag the server reuses
the last user that was run; on first ever run it migrates the existing
hard-coded setup into a user called "nick".

User management (no server is started for these):
    python server.py --list-users        # show all users
    python server.py --new-user NAME      # interactively create a new user
                                          # (asks for favourites, then Claude
                                          #  builds their starting profile)

Requires:
    - ANTHROPIC_API_KEY environment variable
    - pip install -r requirements.txt
    (or use anaconda)
    - conda env create -f environment.yml
    - conda activate book_recommender
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import re
import sys
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Third-party (install via requirements.txt)
try:
    from flask import Flask, jsonify, request, send_from_directory
except ImportError:
    print("ERROR: flask not installed. Run: pip install -r requirements.txt", file=sys.stderr)
    sys.exit(1)

try:
    from anthropic import Anthropic, APIError, APITimeoutError
except ImportError:
    print("ERROR: anthropic not installed. Run: pip install -r requirements.txt", file=sys.stderr)
    sys.exit(1)


# ───────────────────── Configuration ─────────────────────

HERE = Path(__file__).parent.resolve()
USERS_DIR = HERE / "users"
LAST_USER_FILE = HERE / "last_user.txt"
LEGACY_STATE_FILE = HERE / "state.json"   # pre-multi-user single-user state
LOG_FILE = HERE / "server.log"
DEFAULT_PORT = 5050
DEFAULT_USER = "nick"

MODEL = "claude-sonnet-4-6"  # overridden by --model at startup

# Set at startup once a user has been resolved. The web routes operate on
# whichever user the server was launched for.
CURRENT_USER = DEFAULT_USER
PROFILE: dict[str, Any] = {}

MODELS = {
    "sonnet": "claude-sonnet-4-6",
    "haiku":  "claude-haiku-4-5-20251001",
    "opus":   "claude-opus-4-7",
}
MAX_TOKENS = 2048
BOOTSTRAP_MAX_TOKENS = 8192   # new-user profile is a much bigger generation
BATCH_SIZE = 6        # books per Claude call
TIMEOUT_S = 90.0      # per-call timeout
BOOTSTRAP_TIMEOUT_S = 180.0   # building a whole profile can take a while


# ───────────────────── Logging ─────────────────────

class ColourFormatter(logging.Formatter):
    """Add a touch of colour to terminal output."""
    GREY = "\033[90m"
    BLUE = "\033[94m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    RED = "\033[91m"
    BOLD = "\033[1m"
    RESET = "\033[0m"
    LEVEL_COLOUR = {
        "DEBUG": GREY,
        "INFO": BLUE,
        "WARNING": YELLOW,
        "ERROR": RED,
        "CRITICAL": BOLD + RED,
    }

    def format(self, record: logging.LogRecord) -> str:
        ts = self.formatTime(record, "%H:%M:%S")
        colour = self.LEVEL_COLOUR.get(record.levelname, "")
        level = f"{colour}{record.levelname:<5}{self.RESET}"
        return f"{self.GREY}{ts}{self.RESET}  {level}  {record.getMessage()}"


def setup_logging(debug: bool) -> None:
    level = logging.DEBUG if debug else logging.INFO
    root = logging.getLogger()
    root.handlers.clear()
    root.setLevel(level)

    # Stream handler (terminal, with colour)
    sh = logging.StreamHandler(sys.stdout)
    sh.setLevel(level)
    sh.setFormatter(ColourFormatter())
    root.addHandler(sh)

    # File handler (plain text)
    try:
        fh = logging.FileHandler(LOG_FILE, encoding="utf-8")
        fh.setLevel(level)
        fh.setFormatter(logging.Formatter(
            "%(asctime)s %(levelname)-5s %(name)s %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
        ))
        root.addHandler(fh)
    except Exception as e:
        print(f"WARNING: could not open log file {LOG_FILE}: {e}", file=sys.stderr)

    # Quiet down werkzeug's per-request access log; we do our own
    logging.getLogger("werkzeug").setLevel(logging.WARNING)


log = logging.getLogger("recommender")


# ───────────────────── Seed data ─────────────────────
# This hard-coded setup is Nick's original, hand-crafted profile. On the first
# ever run (before any users/ directory exists) it is migrated into a user
# called "nick", together with the existing state.json. After that it is only a
# fallback and new users get their own profiles generated by Claude.

ORIGINAL_FAVOURITES = [
    "Margaret Atwood — Oryx and Crake",
    "William Gibson — The Sprawl Trilogy and most other Gibson",
    "Cormac McCarthy — The Road",
    "Tim Winton — Juice",
    "Paolo Bacigalupi — all books, especially The Water Knife and The Windup Girl",
    "George R. R. Martin — A Game of Thrones",
    "Patrick Rothfuss — The Kingkiller Chronicle",
    "Joe Abercrombie — all books, especially The First Law",
    "Cixin Liu — The Three-Body Problem and the rest of the trilogy",
    "Dan Simmons — the Hyperion Cantos",
    "Robert Harris — all books",
    "Bernard Cornwell — especially the Saxon Stories (Uhtred and Alfred the Great)",
    "Ursula K. Le Guin — sci-fi and fantasy",
    "David Mitchell — Cloud Atlas",
    "Frank Herbert — Dune (and posthumous continuations)",
    "Scott Lynch — Gentleman Bastard / Locke Lamora",
]

GENRES = [
    {"key": "cli-fi", "label": "Climate dystopia", "sub": "For when you want Bacigalupi, Atwood or McCarthy"},
    {"key": "cyber", "label": "Cyberpunk and tech-noir", "sub": "For when you want Gibson"},
    {"key": "space", "label": "Space opera and hard sci-fi", "sub": "For when you want Hyperion, Three Body or Dune"},
    {"key": "fantasy", "label": "Epic fantasy", "sub": "For when you want Abercrombie, GRRM or Lynch"},
    {"key": "historical", "label": "Historical fiction", "sub": "For when you want Cornwell or Harris"},
    {"key": "literary", "label": "Literary speculative", "sub": "For when you want Le Guin or Mitchell"},
]

SEED_BOOKS: list[dict[str, Any]] = [
    # Climate dystopia
    {"id": "parable-of-the-sower", "title": "Parable of the Sower", "author": "Octavia E. Butler", "genre": "cli-fi",
     "why": "Walled communities, climate collapse, a teenage prophet on the road. The bone-deep dread of The Road meets the political thrust of Bacigalupi — and it was written in 1993."},
    {"id": "ministry-future", "title": "The Ministry for the Future", "author": "Kim Stanley Robinson", "genre": "cli-fi",
     "why": "A polyphonic climate novel that opens with a heatwave scene as devastating as anything in The Water Knife, then pivots into oddly hopeful policy wonkery."},
    {"id": "american-war", "title": "American War", "author": "Omar El Akkad", "genre": "cli-fi",
     "why": "A second US civil war in the 2070s, fought over the last fossil fuels. Spare, devastating prose — distinctly McCarthy-coded, with a slow-burn protagonist arc."},
    {"id": "gold-fame-citrus", "title": "Gold Fame Citrus", "author": "Claire Vaye Watkins", "genre": "cli-fi",
     "why": "California's water is gone and a dune sea is swallowing the Southwest. Lyrical and hallucinatory — basically a literary sibling to The Water Knife."},

    # Cyberpunk
    {"id": "snow-crash", "title": "Snow Crash", "author": "Neal Stephenson", "genre": "cyber",
     "why": "Cyberpunk's other foundational text — funnier and faster than Gibson. Samurai pizza couriers, a metaverse linguistic virus, and the best opening 50 pages in the genre."},
    {"id": "altered-carbon", "title": "Altered Carbon", "author": "Richard Morgan", "genre": "cyber",
     "why": "Hard-boiled detective noir plus downloadable consciousness. The Sprawl trilogy's 2000s grandchild — grittier, pulpier, and very confident."},
    {"id": "quantum-thief", "title": "The Quantum Thief", "author": "Hannu Rajaniemi", "genre": "cyber",
     "why": "A post-cyberpunk caper across a transhuman solar system. Dense, dazzling, throws you in the deep end exactly the way Neuromancer did."},
    {"id": "blindsight", "title": "Blindsight", "author": "Peter Watts", "genre": "cyber",
     "why": "First-contact horror with transhumans and predator-vampires interrogating consciousness itself. Brutally smart — Hyperion fans tend to love it too."},

    # Space opera & hard SF
    {"id": "memory-called-empire", "title": "A Memory Called Empire", "author": "Arkady Martine", "genre": "space",
     "why": "A small-station ambassador navigates the seductive horror of a vast empire. Reads like Hyperion crossed with Le Guin's anthropological eye. The sequel is just as good."},
    {"id": "player-of-games", "title": "The Player of Games", "author": "Iain M. Banks", "genre": "space",
     "why": "The friendliest doorway into the Culture. Scope, civilisational politics, and moral weight that should hit your Dune and Hyperion nerve. Banks is the missing author from your list."},
    {"id": "children-of-time", "title": "Children of Time", "author": "Adrian Tchaikovsky", "genre": "space",
     "why": "Uplifted spiders evolve over millennia while a battered generation ship limps toward them. Big-idea SF in Cixin Liu's lineage but with more empathy."},
    {"id": "house-of-suns", "title": "House of Suns", "author": "Alastair Reynolds", "genre": "space",
     "why": "A six-million-year galactic timescale, with clones of a single woman trading memories at meet-ups every 200,000 years. Hyperion-grade scope and melancholy."},

    # Epic fantasy
    {"id": "gardens-of-the-moon", "title": "Gardens of the Moon (Malazan)", "author": "Steven Erikson", "genre": "fantasy",
     "why": "An army-scale, mythologically dense fantasy spread across continents and millennia. Steeper learning curve than First Law but the payoff over ten books is enormous."},
    {"id": "black-company", "title": "The Black Company", "author": "Glen Cook", "genre": "fantasy",
     "why": "Grimdark before grimdark was a word. Mercenary-company POV, blood-and-mud morality — the obvious ancestor of Abercrombie's First Law."},
    {"id": "assassins-apprentice", "title": "Assassin's Apprentice", "author": "Robin Hobb", "genre": "fantasy",
     "why": "Slow-burn, ferocious character work across a 16-book braided saga. The author Rothfuss readers most often graduate to — and she actually finishes her series."},
    {"id": "poppy-war", "title": "The Poppy War", "author": "R. F. Kuang", "genre": "fantasy",
     "why": "Military academy to genocide-scale war, drawn from 20th-century Chinese history. Brutal, modern, GRRM-territory stakes — not for the faint-hearted."},

    # Historical fiction
    {"id": "wolf-hall", "title": "Wolf Hall", "author": "Hilary Mantel", "genre": "historical",
     "why": "Thomas Cromwell's rise in Henry VIII's court. Prose good enough to be illegal, plus all the political cunning of GRRM but in actual history. The trilogy is one of the great achievements."},
    {"id": "shogun", "title": "Shōgun", "author": "James Clavell", "genre": "historical",
     "why": "An Englishman shipwrecked into Sengoku-era Japan. Massive, addictive, written with the same propulsive instinct as Cornwell's Saxon books."},
    {"id": "master-and-commander", "title": "Master and Commander", "author": "Patrick O'Brian", "genre": "historical",
     "why": "Napoleonic naval fiction across 20 books. The more literary cousin of Cornwell's Sharpe — quieter, funnier, profoundly companionable once you tune in to the rhythm."},
    {"id": "hhhh", "title": "HHhH", "author": "Laurent Binet", "genre": "historical",
     "why": "The 1942 plot to assassinate Reinhard Heydrich, told as a meta-narrative about the difficulty of telling it. Slim, riveting — Robert Harris would adore this one."},

    # Literary speculative
    {"id": "piranesi", "title": "Piranesi", "author": "Susanna Clarke", "genre": "literary",
     "why": "A man lives alone in an infinite labyrinth of statues and tides. Short, strange, perfect — Le Guin would have loved it."},
    {"id": "never-let-me-go", "title": "Never Let Me Go", "author": "Kazuo Ishiguro", "genre": "literary",
     "why": "Quiet dystopia disguised as a boarding-school memoir. Devastating in the same way Cloud Atlas is devastating, but more concentrated."},
    {"id": "jonathan-strange", "title": "Jonathan Strange & Mr Norrell", "author": "Susanna Clarke", "genre": "literary",
     "why": "Two magicians revive English magic during the Napoleonic Wars. Footnoted, funny, immense — the texture of Le Guin with the wit of an Austen novel."},
    {"id": "memory-police", "title": "The Memory Police", "author": "Yoko Ogawa", "genre": "literary",
     "why": "On a small island, things vanish from memory one by one — birds, ribbons, novels, body parts. Ishiguro-quiet, Atwood-political, hauntingly beautiful."},
]


# ───────────────────── Users, profiles and state ─────────────────────
#
# Layout on disk:
#     users/<name>/profile.json   favourites, genres, seed_books (the "prompt")
#     users/<name>/state.json     version, current_books, marks, history
#     last_user.txt               name of the most recently launched user
#
# A profile is the personalised setup for a user. The state is their live
# reading list. Keeping them separate means we can regenerate or hand-edit a
# profile without disturbing someone's marks and history.

USER_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,31}$")


def normalise_user_name(name: str) -> str:
    """Lowercase and validate a user name; raise ValueError if unusable."""
    cleaned = (name or "").strip().lower()
    if not USER_NAME_RE.match(cleaned):
        raise ValueError(
            f"invalid user name {name!r}: use 1-32 chars of a-z, 0-9, '-' or '_' "
            f"(starting with a letter or digit)"
        )
    return cleaned


def user_dir(user: str) -> Path:
    return USERS_DIR / user


def profile_path(user: str) -> Path:
    return user_dir(user) / "profile.json"


def state_path(user: str) -> Path:
    return user_dir(user) / "state.json"


def user_exists(user: str) -> bool:
    return profile_path(user).exists()


def list_users() -> list[str]:
    if not USERS_DIR.exists():
        return []
    return sorted(d.name for d in USERS_DIR.iterdir() if (d / "profile.json").exists())


def read_last_user() -> str | None:
    try:
        name = LAST_USER_FILE.read_text(encoding="utf-8").strip()
        return name or None
    except FileNotFoundError:
        return None
    except Exception as e:
        log.warning(f"could not read {LAST_USER_FILE.name}: {e}")
        return None


def write_last_user(user: str) -> None:
    try:
        LAST_USER_FILE.write_text(user + "\n", encoding="utf-8")
    except Exception as e:
        log.warning(f"could not record last user: {e}")


# ── Profiles ──

def default_profile(display_name: str) -> dict[str, Any]:
    """Nick's hand-crafted setup — used only for the first-run migration."""
    return {
        "version": 1,
        "display_name": display_name,
        "original_favourites": list(ORIGINAL_FAVOURITES),
        "genres": [dict(g) for g in GENRES],
        "seed_books": [dict(b) for b in SEED_BOOKS],
    }


def normalise_profile(profile: dict[str, Any], display_name: str) -> dict[str, Any]:
    """Coerce a (possibly Claude-generated) profile into a valid shape.

    Ensures the required keys exist, genres have keys/labels, and every seed
    book has a unique id and a genre that matches one of the declared genres.
    """
    favs = [str(x) for x in profile.get("original_favourites", []) if str(x).strip()]
    genres = []
    seen_keys: set[str] = set()
    for g in profile.get("genres", []):
        key = re.sub(r"[^a-z0-9]+", "-", str(g.get("key", "")).lower()).strip("-")
        if not key or key in seen_keys:
            continue
        seen_keys.add(key)
        genres.append({
            "key": key,
            "label": str(g.get("label", key)).strip() or key,
            "sub": str(g.get("sub", "")).strip(),
        })

    valid_genre_keys = {g["key"] for g in genres}
    fallback_genre = genres[0]["key"] if genres else "general"

    seed_books = []
    taken_ids: set[str] = set()
    for b in profile.get("seed_books", []):
        title = str(b.get("title", "")).strip()
        if not title:
            continue
        genre = str(b.get("genre", "")).strip()
        if genre not in valid_genre_keys:
            genre = fallback_genre
        base = re.sub(r"[^a-z0-9]+", "-", (b.get("id") or title).lower()).strip("-") or "book"
        bid = base
        n = 2
        while bid in taken_ids:
            bid = f"{base}-{n}"
            n += 1
        taken_ids.add(bid)
        seed_books.append({
            "id": bid,
            "title": title,
            "author": str(b.get("author", "Unknown")).strip() or "Unknown",
            "genre": genre,
            "why": str(b.get("why", "")).strip(),
        })

    return {
        "version": 1,
        "display_name": display_name,
        "original_favourites": favs,
        "genres": genres,
        "seed_books": seed_books,
    }


def save_profile(user: str, profile: dict[str, Any]) -> None:
    user_dir(user).mkdir(parents=True, exist_ok=True)
    path = profile_path(user)
    tmp = path.with_suffix(".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(profile, f, indent=2, ensure_ascii=False)
    tmp.replace(path)
    log.debug(
        f"saved profile for {user!r}: {len(profile.get('original_favourites', []))} favourites, "
        f"{len(profile.get('genres', []))} genres, {len(profile.get('seed_books', []))} seed books"
    )


def load_profile(user: str) -> dict[str, Any]:
    path = profile_path(user)
    with path.open("r", encoding="utf-8") as f:
        profile = json.load(f)
    for key in ("original_favourites", "genres", "seed_books"):
        if key not in profile:
            raise ValueError(f"profile for {user!r} is missing key: {key}")
    profile.setdefault("display_name", user)
    return profile


# ── State ──

def default_state(profile: dict[str, Any]) -> dict[str, Any]:
    return {
        "version": 1,
        "current_books": [dict(b) for b in profile.get("seed_books", [])],
        "marks": {},
        "history": [],
    }


def load_state(user: str, profile: dict[str, Any]) -> dict[str, Any]:
    path = state_path(user)
    if not path.exists():
        log.info(f"No state file for {user!r} — creating fresh state from profile")
        st = default_state(profile)
        save_state(user, st)
        return st

    try:
        with path.open("r", encoding="utf-8") as f:
            st = json.load(f)
        for key in ("current_books", "marks", "history"):
            if key not in st:
                raise ValueError(f"missing key: {key}")
        return st
    except Exception as e:
        backup = path.with_suffix(f".corrupt-{int(time.time())}.json")
        log.error(f"State file for {user!r} corrupt ({e}). Backing up to {backup.name} and starting fresh.")
        try:
            path.rename(backup)
        except Exception as ee:
            log.error(f"Could not rename corrupt state file: {ee}")
        st = default_state(profile)
        save_state(user, st)
        return st


def save_state(user: str, state: dict[str, Any]) -> None:
    user_dir(user).mkdir(parents=True, exist_ok=True)
    path = state_path(user)
    tmp = path.with_suffix(".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(state, f, indent=2, ensure_ascii=False)
    tmp.replace(path)
    log.debug(
        f"saved state for {user!r}: {len(state['current_books'])} books, "
        f"{len(state['marks'])} marks, {len(state['history'])} history"
    )


# ── First-run migration ──

def migrate_legacy_if_needed() -> None:
    """Ensure the old single-user setup survives as user 'nick'.

    Two cases, both idempotent (safe to call on every startup):

    1. Upgrade from the old single-user app: a state.json exists but nick has
       not been created yet. Nick's hand-crafted profile becomes
       users/nick/profile.json and the existing state.json (his marks, history
       and current list) becomes users/nick/state.json — nothing is lost. The
       old state.json is then renamed to a timestamped backup.

    2. A completely fresh install (no state.json and no users at all): seed a
       default 'nick' from the built-in book list, matching the app's previous
       first-run behaviour so there is always something to open.

    Once nick exists and the legacy file has been backed up, neither case
    fires again.
    """
    legacy_pending = LEGACY_STATE_FILE.exists() and not user_exists(DEFAULT_USER)
    fresh_install = not USERS_DIR.exists() and not LEGACY_STATE_FILE.exists()
    if not (legacy_pending or fresh_install):
        return

    log.info("Setting up multi-user storage — ensuring user 'nick' exists")
    profile = default_profile("Nick")
    save_profile(DEFAULT_USER, profile)

    if legacy_pending:
        try:
            with LEGACY_STATE_FILE.open("r", encoding="utf-8") as f:
                legacy = json.load(f)
            for key in ("current_books", "marks", "history"):
                if key not in legacy:
                    raise ValueError(f"legacy state missing key: {key}")
            save_state(DEFAULT_USER, legacy)
            backup = LEGACY_STATE_FILE.with_name(f"state.json.pre-multiuser-{int(time.time())}")
            LEGACY_STATE_FILE.rename(backup)
            log.info(
                f"  migrated existing state ({len(legacy['current_books'])} books, "
                f"{len(legacy['history'])} history) → {state_path(DEFAULT_USER)}"
            )
            log.info(f"  old state.json preserved as {backup.name}")
        except Exception as e:
            log.error(f"Could not migrate legacy state.json ({e}); starting nick from seed books")
            save_state(DEFAULT_USER, default_state(profile))
    else:
        log.info("  fresh install — seeding nick from the built-in book list")
        save_state(DEFAULT_USER, default_state(profile))


# ───────────────────── Claude integration ─────────────────────

SYSTEM_PROMPT = """You recommend books. The user gives you a list of their original favourite books and authors, a list of titles to avoid, and a list of "slots to replace" — each slot has a genre and a mark indicating how the user reacted to the book it's replacing. For each slot, return one new recommendation.

Output format: your entire reply must be a single JSON array. The first character must be [ and the last must be ]. No prose, no preamble, no code fences, no commentary.

Each element must be an object with exactly these fields:
{"title": string, "author": string, "genre": "cli-fi"|"cyber"|"space"|"fantasy"|"historical"|"literary", "why": string}

The "why" field is 1-2 short sentences tying the pick to a specific original favourite or to the book being replaced.

Rules per replacement:
- "genre" must equal the slot's genre exactly
- The book must NOT appear in originalFavourites or avoidTitles
- mark = "loved": pick something stylistically adjacent (same vibe, voice, themes)
- mark = "passed": pick something in the same genre but with a clearly different style or approach
- mark = "read": pick a strong adjacent book that broadens exposure
- Lesser-known, translated, and out-of-print picks are welcome
"""


BOOTSTRAP_SYSTEM_PROMPT = """You set up a personalised book recommender for a new user. You are given the user's favourite books and authors, and optionally a hint about the kinds of genres they enjoy. Build their starting profile.

Output format: your entire reply must be a single JSON object. The first character must be { and the last must be }. No prose, no preamble, no code fences, no commentary.

The object must have exactly these fields:
{
  "original_favourites": [string, ...],
  "genres": [ {"key": string, "label": string, "sub": string}, ... ],
  "seed_books": [ {"id": string, "title": string, "author": string, "genre": string, "why": string}, ... ]
}

Requirements:
- "original_favourites": 10-16 entries, each a tidied "Author — Work or note" line derived from what the user told you. Keep their own books here.
- "genres": exactly 6. "key" is a short lowercase-kebab slug (e.g. "space", "cli-fi"). "label" is a human title (e.g. "Space opera and hard sci-fi"). "sub" is a short hint like "For when you want X", referencing one of the user's favourites. Genres must reflect the user's stated tastes (and the genre hint if given).
- "seed_books": exactly 24 — exactly 4 per genre. "genre" must equal one of the genre keys above. "id" is a unique lowercase-kebab slug. "why" is 1-2 sentences tying the pick to a specific favourite author/book or to the genre.
- seed_books must NOT include any book already listed in original_favourites.
- Lesser-known, translated, and out-of-print picks are welcome.
"""


def call_claude(
    payload: dict[str, Any],
    *,
    system: str = SYSTEM_PROMPT,
    max_tokens: int = MAX_TOKENS,
    timeout: float = TIMEOUT_S,
) -> str:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY environment variable is not set")

    client = Anthropic(api_key=api_key, timeout=timeout)
    user_content = json.dumps(payload, indent=2, ensure_ascii=False)

    log.info(
        f"→ Claude  model={MODEL}  prompt_chars={len(user_content)}  "
        f"slots={len(payload.get('slotsToReplace', []))}"
    )
    log.debug(f"full prompt:\n{user_content}")

    t0 = time.time()
    try:
        response = client.messages.create(
            model=MODEL,
            max_tokens=max_tokens,
            system=system,
            messages=[{"role": "user", "content": user_content}],
        )
    except APITimeoutError as e:
        elapsed = time.time() - t0
        log.error(f"× Claude timed out after {elapsed:.1f}s: {e}")
        raise
    except APIError as e:
        elapsed = time.time() - t0
        log.error(f"× Claude API error after {elapsed:.1f}s: {type(e).__name__}: {e}")
        raise

    elapsed = time.time() - t0
    text = response.content[0].text
    usage = getattr(response, "usage", None)
    usage_str = ""
    if usage is not None:
        usage_str = f"  in_tok={getattr(usage, 'input_tokens', '?')}  out_tok={getattr(usage, 'output_tokens', '?')}"
    log.info(f"← Claude  latency={elapsed:.1f}s  resp_chars={len(text)}{usage_str}")
    log.debug(f"raw response:\n{text}")

    return text


def parse_picks(text: str) -> list[dict[str, Any]] | None:
    """Forgiving parser: handles fences, object-wrapping, leading commentary."""
    s = text.strip()
    s = re.sub(r"^```(?:json|javascript|js)?\s*", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\s*```\s*$", "", s, flags=re.IGNORECASE).strip()

    # Direct parse
    try:
        parsed = json.loads(s)
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, dict):
            for v in parsed.values():
                if isinstance(v, list):
                    return v
    except json.JSONDecodeError as e:
        log.debug(f"direct parse failed: {e}")

    # Balanced array extraction
    start = s.find("[")
    if start < 0:
        return None
    depth, in_string, escape = 0, False, False
    for i in range(start, len(s)):
        ch = s[i]
        if escape:
            escape = False
            continue
        if ch == "\\":
            escape = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(s[start : i + 1])
                except json.JSONDecodeError as e:
                    log.debug(f"balanced parse failed: {e}")
                    return None
    return None


def make_unique_id(title: str, state: dict[str, Any]) -> str:
    base = re.sub(r"[^a-z0-9]+", "-", (title or "untitled").lower()).strip("-") or "untitled"
    taken = {b["id"] for b in state["current_books"]} | {h.get("id", "") for h in state["history"]}
    if base not in taken:
        return base
    n = 2
    while f"{base}-{n}" in taken:
        n += 1
    return f"{base}-{n}"


def label_for_mark(m: dict[str, Any]) -> str:
    if m.get("like") == "love":
        return "loved"
    if m.get("like") == "meh":
        return "passed"
    return "read"


def parse_json_object(text: str) -> dict[str, Any] | None:
    """Forgiving parser for a single JSON object (used for new-user profiles)."""
    s = text.strip()
    s = re.sub(r"^```(?:json|javascript|js)?\s*", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\s*```\s*$", "", s, flags=re.IGNORECASE).strip()

    try:
        parsed = json.loads(s)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError as e:
        log.debug(f"direct object parse failed: {e}")

    start = s.find("{")
    if start < 0:
        return None
    depth, in_string, escape = 0, False, False
    for i in range(start, len(s)):
        ch = s[i]
        if escape:
            escape = False
            continue
        if ch == "\\":
            escape = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(s[start : i + 1])
                except json.JSONDecodeError as e:
                    log.debug(f"balanced object parse failed: {e}")
                    return None
    return None


# ───────────────────── New-user creation (CLI) ─────────────────────

def _prompt_multiline(prompt: str) -> str:
    """Read lines from stdin until a blank line or EOF."""
    print(prompt)
    lines: list[str] = []
    while True:
        try:
            line = input()
        except EOFError:
            break
        if line.strip() == "":
            break
        lines.append(line)
    return "\n".join(lines).strip()


def generate_profile(favourites_text: str, genre_hint: str, display_name: str) -> dict[str, Any]:
    """Ask Claude to build a starting profile from the user's stated tastes."""
    payload: dict[str, Any] = {"favourites": favourites_text}
    if genre_hint:
        payload["genreHint"] = genre_hint

    text = call_claude(
        payload,
        system=BOOTSTRAP_SYSTEM_PROMPT,
        max_tokens=BOOTSTRAP_MAX_TOKENS,
        timeout=BOOTSTRAP_TIMEOUT_S,
    )
    raw = parse_json_object(text)
    if not raw:
        raise ValueError(
            "could not parse a JSON profile from Claude's response.\n"
            f"First 500 chars of response:\n{text[:500]}"
        )
    profile = normalise_profile(raw, display_name)
    if not profile["genres"] or not profile["seed_books"]:
        raise ValueError("Claude returned a profile with no usable genres or seed books")
    return profile


def create_user_interactive(name: str) -> None:
    """Interactively create a new user: collect tastes, generate a profile."""
    try:
        user = normalise_user_name(name)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    if user_exists(user):
        print(f"User {user!r} already exists ({profile_path(user)}). Choose another name.", file=sys.stderr)
        sys.exit(1)

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY is not set — needed to build the new user's profile.", file=sys.stderr)
        sys.exit(1)

    print("═" * 60)
    print(f"Creating a new book-recommender user: {user!r}")
    print("═" * 60)
    display_name = input("Display name (press Enter to use the user name): ").strip() or user

    favourites_text = _prompt_multiline(
        "\nList this person's favourite books and authors — one per line, free-form.\n"
        "Example:\n"
        "  Ursula K. Le Guin, especially The Left Hand of Darkness\n"
        "  Cormac McCarthy — The Road\n"
        "Finish with a blank line:"
    )
    if not favourites_text:
        print("No favourites given — cannot build a profile. Aborting.", file=sys.stderr)
        sys.exit(1)

    genre_hint = input(
        "\n(Optional) Any genres to emphasise? e.g. 'fantasy, literary, sci-fi'.\n"
        "Press Enter to let Claude choose: "
    ).strip()

    print(f"\nAsking Claude (model {MODEL}) to build a starting profile — this can take a minute…")
    try:
        profile = generate_profile(favourites_text, genre_hint, display_name)
    except Exception as e:
        print(f"\nFailed to build profile: {e}", file=sys.stderr)
        sys.exit(1)

    save_profile(user, profile)
    save_state(user, default_state(profile))
    write_last_user(user)

    print("\n" + "─" * 60)
    print(f"Created user {user!r} ({display_name}):")
    print(f"  {len(profile['original_favourites'])} favourites")
    print(f"  {len(profile['genres'])} genres: " + ", ".join(g["label"] for g in profile["genres"]))
    print(f"  {len(profile['seed_books'])} seed books")
    print(f"  profile : {profile_path(user)}")
    print(f"  state   : {state_path(user)}")
    print("─" * 60)
    print(f"\nStart the server for this user with:\n    python server.py --user {user}")
    print("(Edit the profile.json by hand any time to fine-tune the favourites, genres or seed books.)")


# ───────────────────── Flask app ─────────────────────

app = Flask(__name__, static_folder=None)


@app.before_request
def _log_request() -> None:
    log.debug(f"→ {request.method} {request.path}")


@app.after_request
def _log_response(resp):
    log.debug(f"← {resp.status_code} {request.method} {request.path}")
    return resp


@app.route("/")
def index():
    return send_from_directory(HERE, "index.html")


@app.route("/api/state", methods=["GET"])
def api_get_state():
    state = load_state(CURRENT_USER, PROFILE)
    return jsonify(
        {
            "current_books": state["current_books"],
            "marks": state["marks"],
            "history": state["history"],
            "genres": PROFILE["genres"],
            "original_favourites": PROFILE["original_favourites"],
            "model": MODEL,
            "user": CURRENT_USER,
            "display_name": PROFILE.get("display_name", CURRENT_USER),
            "users": list_users(),
        }
    )


@app.route("/api/users", methods=["GET"])
def api_users():
    return jsonify({
        "users": list_users(),
        "current": CURRENT_USER,
        "display_name": PROFILE.get("display_name", CURRENT_USER),
    })


@app.route("/api/mark", methods=["POST"])
def api_mark():
    body = request.get_json(silent=True) or {}
    book_id = body.get("id")
    patch = body.get("patch", {}) or {}
    if not book_id or not isinstance(patch, dict):
        return jsonify({"ok": False, "error": "Missing id or patch"}), 400

    log.info(f"mark  user={CURRENT_USER!r}  id={book_id!r}  patch={patch}")

    state = load_state(CURRENT_USER, PROFILE)
    cur = state["marks"].get(book_id, {"read": False, "like": None})
    cur = {**cur, **patch}
    if patch.get("like") in ("love", "meh"):
        cur["read"] = True
    state["marks"][book_id] = cur
    save_state(CURRENT_USER, state)
    return jsonify({"ok": True, "marks": state["marks"]})


@app.route("/api/clear-marks", methods=["POST"])
def api_clear_marks():
    log.info(f"clear all marks  user={CURRENT_USER!r}")
    state = load_state(CURRENT_USER, PROFILE)
    state["marks"] = {}
    save_state(CURRENT_USER, state)
    return jsonify({"ok": True, "marks": state["marks"]})


@app.route("/api/clear-history", methods=["POST"])
def api_clear_history():
    log.info(f"clear history  user={CURRENT_USER!r}")
    state = load_state(CURRENT_USER, PROFILE)
    state["history"] = []
    save_state(CURRENT_USER, state)
    return jsonify({"ok": True, "history": state["history"]})


@app.route("/api/fresh-picks", methods=["POST"])
def api_fresh_picks():
    state = load_state(CURRENT_USER, PROFILE)
    original_favourites = PROFILE["original_favourites"]
    marked_books = [
        b for b in state["current_books"]
        if (m := state["marks"].get(b["id"])) and (m.get("read") or m.get("like"))
    ]
    if not marked_books:
        log.warning("fresh-picks called with no marked books")
        return jsonify({"ok": False, "error": "No marked books to replace."}), 400

    log.info(f"fresh-picks  marked={len(marked_books)}")

    avoid_titles = (
        [f"{b['title']} by {b['author']}" for b in state["current_books"]]
        + [f"{h['title']} by {h['author']}" for h in state["history"]]
    )
    loved_so_far = [
        f"{b['title']} by {b['author']}"
        for b in state["current_books"]
        if state["marks"].get(b["id"], {}).get("like") == "love"
    ]
    passed_so_far = [
        f"{b['title']} by {b['author']}"
        for b in state["current_books"]
        if state["marks"].get(b["id"], {}).get("like") == "meh"
    ]

    slots = []
    for b in marked_books:
        m = state["marks"][b["id"]]
        slots.append(
            {
                "genre": b["genre"],
                "replacing": f"{b['title']} by {b['author']}",
                "mark": label_for_mark(m),
            }
        )

    batches = [slots[i : i + BATCH_SIZE] for i in range(0, len(slots), BATCH_SIZE)]
    log.info(f"split into {len(batches)} batch(es) of up to {BATCH_SIZE}")

    all_picks: list[dict[str, Any]] = []
    last_response = ""
    error: str | None = None

    for bi, batch in enumerate(batches, start=1):
        log.info(f"  batch {bi}/{len(batches)}: {len(batch)} slot(s)")
        payload = {
            "originalFavourites": original_favourites,
            "avoidTitles": avoid_titles,
            "lovedSoFar": loved_so_far,
            "passedSoFar": passed_so_far,
            "slotsToReplace": batch,
        }
        try:
            text = call_claude(payload)
            last_response = text
            picks = parse_picks(text)
            if not picks:
                raise ValueError("could not parse JSON array from response")
            log.info(f"  batch {bi}/{len(batches)}: parsed {len(picks)} picks")
            all_picks.extend(picks[: len(batch)])
        except Exception as e:
            error = f"{type(e).__name__}: {e}"
            log.error(f"× batch {bi}/{len(batches)} failed: {error}")
            log.debug(traceback.format_exc())
            break

    # Apply replacements (only for picks we successfully got)
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    replaced: list[dict[str, Any]] = []
    for old_book, pick in zip(marked_books, all_picks):
        m = state["marks"].get(old_book["id"], {})

        # Add old book to history
        state["history"].insert(
            0,
            {
                "id": old_book["id"],
                "title": old_book["title"],
                "author": old_book["author"],
                "genre": old_book["genre"],
                "mark": label_for_mark(m),
                "replaced_at": now,
            },
        )

        # Build replacement
        new_id = make_unique_id(pick.get("title", ""), state)
        new_book = {
            "id": new_id,
            "title": str(pick.get("title", "Untitled")),
            "author": str(pick.get("author", "Unknown")),
            "genre": old_book["genre"],  # force genre to match slot
            "why": str(pick.get("why", "")),
            "is_fresh": True,
        }

        # Replace in place
        for i, b in enumerate(state["current_books"]):
            if b["id"] == old_book["id"]:
                state["current_books"][i] = new_book
                break

        # Clear mark for the old slot id
        state["marks"].pop(old_book["id"], None)
        replaced.append({"old": old_book, "new": new_book})
        log.info(
            f"  replaced [{old_book['genre']}] "
            f"{old_book['title']!r} ({label_for_mark(m)}) → {new_book['title']!r} by {new_book['author']}"
        )

    save_state(CURRENT_USER, state)
    log.info(f"fresh-picks done  user={CURRENT_USER!r}  replaced={len(replaced)}/{len(marked_books)}  error={error or 'none'}")

    return jsonify(
        {
            "ok": error is None,
            "replaced_count": len(replaced),
            "marked_count": len(marked_books),
            "error": error,
            "last_response_preview": (last_response[:500] if error else None),
            "marks": state["marks"],
            "current_books": state["current_books"],
            "history": state["history"],
        }
    )


@app.route("/api/test", methods=["GET"])
def api_test():
    """Quick connectivity check: minimal Claude call."""
    log.info("test-api  pinging Claude with a 1-token prompt")
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return jsonify({"ok": False, "error": "ANTHROPIC_API_KEY not set"}), 500
    try:
        client = Anthropic(api_key=api_key, timeout=20.0)
        t0 = time.time()
        resp = client.messages.create(
            model=MODEL,
            max_tokens=20,
            messages=[{"role": "user", "content": "Reply with exactly: OK"}],
        )
        elapsed = time.time() - t0
        text = resp.content[0].text
        log.info(f"test-api OK  latency={elapsed:.1f}s  reply={text!r}")
        return jsonify({"ok": True, "latency_s": round(elapsed, 2), "reply": text, "model": MODEL})
    except Exception as e:
        log.error(f"test-api failed: {type(e).__name__}: {e}")
        log.debug(traceback.format_exc())
        return jsonify({"ok": False, "error": f"{type(e).__name__}: {e}"}), 500


@app.errorhandler(Exception)
def _handle_exception(e):
    log.error(f"unhandled exception in {request.method} {request.path}: {type(e).__name__}: {e}")
    log.error(traceback.format_exc())
    return jsonify({"ok": False, "error": f"{type(e).__name__}: {e}"}), 500


# ───────────────────── Entry point ─────────────────────

def resolve_user(requested: str | None) -> str:
    """Decide which user to run as.

    Precedence: explicit --user, then the last-used user, then 'nick', then the
    sole user if there is exactly one. Exits with a helpful message otherwise.
    """
    available = list_users()

    if requested is not None:
        try:
            user = normalise_user_name(requested)
        except ValueError as e:
            log.error(str(e))
            sys.exit(1)
        if not user_exists(user):
            log.error(f"No such user: {user!r}.")
            if available:
                log.error(f"Available users: {', '.join(available)}")
            log.error(f"Create one with:  python server.py --new-user {user}")
            sys.exit(1)
        return user

    last = read_last_user()
    if last and user_exists(last):
        return last

    if user_exists(DEFAULT_USER):
        return DEFAULT_USER

    if len(available) == 1:
        return available[0]

    log.error("No user could be selected.")
    if available:
        log.error(f"Pick one with --user. Available users: {', '.join(available)}")
    else:
        log.error("There are no users yet. Create one with:  python server.py --new-user NAME")
    sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description="Local book recommender server")
    parser.add_argument("--debug", action="store_true", help="Verbose debug logging")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--model", choices=["sonnet", "haiku", "opus"], default="sonnet",
                        help="Claude model to use (default: sonnet)")
    parser.add_argument("--user", default=None,
                        help="Which user to run as (default: the last user, then 'nick')")
    parser.add_argument("--new-user", metavar="NAME", default=None,
                        help="Interactively create a new user, then exit")
    parser.add_argument("--list-users", action="store_true",
                        help="List all users, then exit")
    args = parser.parse_args()

    global MODEL, CURRENT_USER, PROFILE
    MODEL = MODELS[args.model]

    setup_logging(args.debug)

    # First-run migration of the old single-user setup into user "nick".
    migrate_legacy_if_needed()

    # ── User-management sub-commands (no server) ──
    if args.list_users:
        users = list_users()
        last = read_last_user()
        if not users:
            print("No users yet. Create one with:  python server.py --new-user NAME")
        else:
            print("Users:")
            for u in users:
                marks = []
                if u == last:
                    marks.append("last used")
                if u == DEFAULT_USER:
                    marks.append("default")
                suffix = f"  ({', '.join(marks)})" if marks else ""
                print(f"  {u}{suffix}")
        return

    if args.new_user is not None:
        create_user_interactive(args.new_user)
        return

    # ── Resolve and load the user we'll serve ──
    CURRENT_USER = resolve_user(args.user)
    try:
        PROFILE = load_profile(CURRENT_USER)
    except Exception as e:
        log.error(f"Could not load profile for {CURRENT_USER!r}: {e}")
        sys.exit(1)
    write_last_user(CURRENT_USER)

    log.info("═" * 60)
    log.info("Book recommender server")
    log.info(f"  working dir : {HERE}")
    log.info(f"  user        : {CURRENT_USER}  ({PROFILE.get('display_name', CURRENT_USER)})")
    log.info(f"  profile     : {profile_path(CURRENT_USER)}")
    log.info(f"  state file  : {state_path(CURRENT_USER)}")
    log.info(f"  log file    : {LOG_FILE}")
    log.info(f"  model       : {MODEL}")
    log.info(f"  batch size  : {BATCH_SIZE}")
    log.info(f"  timeout     : {TIMEOUT_S}s per call")
    other_users = [u for u in list_users() if u != CURRENT_USER]
    if other_users:
        log.info(f"  other users : {', '.join(other_users)}  (switch with --user)")

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        log.error("ANTHROPIC_API_KEY environment variable is not set.")
        log.error("Set it with:  export ANTHROPIC_API_KEY=sk-ant-...")
        sys.exit(1)
    masked = f"{api_key[:10]}…{api_key[-4:]}" if len(api_key) > 14 else "(short key)"
    log.info(f"  api key     : {masked}")

    log.info(f"  listening on: http://localhost:{args.port}")
    log.info(f"  open this URL in your browser to use the app:")
    log.info(f"     http://localhost:{args.port}")
    log.info("═" * 60)

    try:
        app.run(host="127.0.0.1", port=args.port, debug=args.debug, use_reloader=False)
    except OSError as e:
        if "Address already in use" in str(e) or getattr(e, "errno", None) == 48:
            log.error(f"Port {args.port} is already in use. Try: python server.py --port {args.port + 1}")
            sys.exit(1)
        raise


if __name__ == "__main__":
    main()
